// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package src

import ()

type Todo struct {
	ID      int64  `json:"id"`
	Content string `json:"content"`
	Done    bool   `json:"done"`
}
